version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ziplink
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Maktab
    networks:
      - shortylink-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ziplink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Maktab
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ziplink-network

networks:
  ziplink-network:
    driver: bridge

volumes:
  postgres-data: